# pull python base image
FROM python:3.10

# copy application files
ADD . .

# specify working directory
WORKDIR /adultcensus_model

# update pip
RUN pip install --upgrade pip

# install dependencies
RUN pip install -r ./../requirements/requirements.txt

# start training model
CMD ["python", "train_pipeline.py"]