name: Adult Census Classification CD Pipeline

# Only trigger when the build workflow succeeds, i.e., CI Pipeline
on:
  workflow_run:
    workflows: ["Train Adult Census Classification Model"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - uses: actions/download-artifact@v2
        with:
          name: my-trained-pipeline
          path: adultcensus_model/trained_models
      
      - name: Install dependencies
        run: pip install --upgrade build
      
      - name: Build package
        run: python -m build
      
      - uses: actions/upload-artifact@v2
        with:
          name: my-build-package
          path: dist/*.whl
          retention-days: 1

  create-image:
    needs: [build]
    if: always()
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - uses: actions/download-artifact@v2
        with:
          name: my-trained-pipeline
          path: adultcensus_model/trained_models
      
      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
      - name: Build the Docker image for FastAPI app
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker build . -f Dockerfile.deploy -t $DOCKER_USER/adultcensus-fastapi:latest
      
      - name: Push the Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: docker push $DOCKER_USER/adultcensus-fastapi
      
      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    needs: [build, create-image]
    if: always()
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/adultcensus-fastapi:latest

      - name: Stop previous Docker Container
        run: sudo docker stop adultcensus-fastapi-container || true

      - name: Delete Old Docker Container
        run: sudo docker rm -f adultcensus-fastapi-container || true

      - name: Run Docker Container
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name adultcensus-fastapi-container $DOCKER_USER/adultcensus-fastapi:latest
