name: Train Model

on:
  push:
    paths:
      - 'adultcensus_model/datasets/**'  # Trigger on new data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt

      - name: Run Training Script
        run: |
          python adultcensus_model/train_pipeline.py
      - name: Run Evaluation Script
        run: |
          python adultcensus_model/evaluate.py

